---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: knative-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - resourcequotas
      - limitranges
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioner
roleRef:
  kind: ClusterRole
  name: provisioner
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: provisioner
    namespace: knative-provisioner